import type { ChatCompletionTool } from "openai/resources/chat/completions";
import { db, isDatabaseAvailable } from "@szl-holdings/db";
import { nimbusPredictionsTable, nimbusAlertsTable } from "@szl-holdings/db/schema";
import { desc } from "drizzle-orm";

export const nimbusTools: ChatCompletionTool[] = [
  {
    type: "function",
    function: {
      name: "list_predictions",
      description: "List AI predictions generated by Nimbus",
      parameters: { type: "object", properties: {}, required: [] },
    },
  },
  {
    type: "function",
    function: {
      name: "list_alerts",
      description: "List system alerts from Nimbus anomaly detection",
      parameters: { type: "object", properties: {}, required: [] },
    },
  },
];

export async function nimbusExecuteTool(name: string, _args: Record<string, unknown>): Promise<string> {
  if (!isDatabaseAvailable()) return JSON.stringify({ error: "Database not available" });
  switch (name) {
    case "list_predictions": {
      const rows = await db.select().from(nimbusPredictionsTable).orderBy(desc(nimbusPredictionsTable.createdAt)).limit(20);
      return JSON.stringify({ predictions: rows, count: rows.length });
    }
    case "list_alerts": {
      const rows = await db.select().from(nimbusAlertsTable).orderBy(desc(nimbusAlertsTable.createdAt)).limit(20);
      return JSON.stringify({ alerts: rows, count: rows.length });
    }
    default:
      return JSON.stringify({ error: `Unknown tool: ${name}` });
  }
}
