import { Router, type Request, type Response } from "express";
import { logger } from "../lib/logger";

const router = Router();

const catalog = [
  {
    name: "ROSIE",
    slug: "rosie",
    description: "AI-powered security monitoring with real-time threat detection, incident response automation, and the Alloy AI chat assistant.",
    category: "Security",
    status: "Active",
    maturity: "Production",
    environment: "Production",
    icon: "Shield",
    color: "from-cyan-500 to-violet-600",
    demoUrl: "/rosie/",
    tags: ["React", "TypeScript", "AI", "Security"],
    features: ["Real-time threat detection", "Incident response", "Alloy AI Assistant", "Vulnerability scanning"],
    health: { status: "healthy", uptime: 99.97, responseTime: 142 },
  },
  {
    name: "Aegis",
    slug: "aegis",
    description: "Enterprise defensive security platform with threat assessment, vulnerability scanning, and compliance monitoring.",
    category: "Security",
    status: "Active",
    maturity: "Production",
    environment: "Production",
    icon: "Shield",
    color: "from-amber-500 to-yellow-600",
    demoUrl: "/aegis/",
    tags: ["Security", "Zero-Trust", "React"],
    features: ["Threat assessment", "Vulnerability scanner", "Compliance monitoring", "Security policies"],
    health: { status: "healthy", uptime: 99.95, responseTime: 156 },
  },
  {
    name: "Beacon",
    slug: "beacon",
    description: "Centralized telemetry and analytics dashboard with KPI tracking, project management, and cross-platform insights.",
    category: "Analytics",
    status: "Active",
    maturity: "Production",
    environment: "Production",
    icon: "BarChart3",
    color: "from-cyan-400 to-blue-600",
    demoUrl: "/beacon/",
    tags: ["Analytics", "Dashboard", "Charts"],
    features: ["KPI tracking", "Project management", "Analytics engine", "Data export"],
    health: { status: "healthy", uptime: 99.98, responseTime: 128 },
  },
  {
    name: "Zeus",
    slug: "zeus",
    description: "Modular core architecture engine powering the entire SZL ecosystem with adaptive scaling and health monitoring.",
    category: "Infrastructure",
    status: "Active",
    maturity: "Production",
    environment: "Production",
    icon: "Zap",
    color: "from-yellow-500 to-amber-600",
    demoUrl: "/zeus/",
    tags: ["Infrastructure", "Modules", "TypeScript"],
    features: ["Module registry", "Health monitoring", "Auto-scaling", "Dependency graph"],
    health: { status: "healthy", uptime: 99.99, responseTime: 98 },
  },
  {
    name: "Nimbus",
    slug: "nimbus",
    description: "Predictive intelligence platform with confidence-scored AI forecasting, anomaly detection, and system alerts.",
    category: "AI/ML",
    status: "Active",
    maturity: "Production",
    environment: "Production",
    icon: "Brain",
    color: "from-cyan-500 to-violet-600",
    demoUrl: "/nimbus/",
    tags: ["AI", "Predictions", "Analytics"],
    features: ["Predictive forecasting", "Anomaly detection", "Smart alerts", "Model pipeline"],
    health: { status: "healthy", uptime: 99.96, responseTime: 134 },
  },
  {
    name: "Vessels",
    slug: "vessels",
    description: "Maritime fleet intelligence with real-time tracking, route optimization, compliance automation, and risk analysis.",
    category: "Operations",
    status: "Active",
    maturity: "Production",
    environment: "Production",
    icon: "Ship",
    color: "from-blue-500 to-emerald-600",
    demoUrl: "/vessels/",
    tags: ["Logistics", "Maps", "Real-time"],
    features: ["Fleet tracking", "Route optimization", "Compliance tracker", "Risk analysis"],
    health: { status: "warning", uptime: 99.90, responseTime: 155 },
  },
  {
    name: "INCA",
    slug: "inca",
    description: "Intelligence platform for experiment tracking, signal processing, and strategic threat correlation analysis.",
    category: "AI/ML",
    status: "Active",
    maturity: "Production",
    environment: "Production",
    icon: "Brain",
    color: "from-emerald-500 to-cyan-600",
    demoUrl: "/inca/",
    tags: ["Intelligence", "ML", "Experiments"],
    features: ["Experiment tracking", "Signal processing", "Threat correlation", "Real-time alerts"],
    health: { status: "healthy", uptime: 99.94, responseTime: 118 },
  },
  {
    name: "Firestorm",
    slug: "firestorm",
    description: "Offensive security simulation lab with attack scenario modeling, detection coverage analysis, and incident playback.",
    category: "Security",
    status: "Active",
    maturity: "Beta",
    environment: "Staging",
    icon: "Flame",
    color: "from-orange-500 to-red-600",
    demoUrl: "/firestorm/",
    tags: ["Security", "Red Team", "Simulation"],
    features: ["Scenario builder", "Attack simulation", "Detection coverage", "Report generation"],
    health: { status: "degraded", uptime: 99.82, responseTime: 203 },
  },
  {
    name: "DreamEra",
    slug: "dreamera",
    description: "AI-powered creative content engine with storytelling, campaign management, and neural synthesis pipeline.",
    category: "AI/ML",
    status: "Active",
    maturity: "Production",
    environment: "Production",
    icon: "Sparkles",
    color: "from-pink-500 to-violet-600",
    demoUrl: "/dreamera/",
    tags: ["AI", "Creative", "Content"],
    features: ["Story engine", "Campaign manager", "Neural synthesis", "Content pipeline"],
    health: { status: "healthy", uptime: 99.89, responseTime: 178 },
  },
  {
    name: "Dreamscape",
    slug: "dreamscape",
    description: "Creative systems platform for world exploration, artifact galleries, and AI-generated content with prompt studios.",
    category: "AI/ML",
    status: "Active",
    maturity: "Beta",
    environment: "Production",
    icon: "Globe",
    color: "from-indigo-500 to-purple-600",
    demoUrl: "/dreamscape/",
    tags: ["Creative", "AI", "Generative"],
    features: ["World explorer", "Artifact gallery", "Prompt studio", "AI generation"],
    health: { status: "healthy", uptime: 99.80, responseTime: 165 },
  },
  {
    name: "AlloyScape",
    slug: "alloyscape",
    description: "AI agent orchestration and infrastructure platform managing the Alloy conversation system across all applications.",
    category: "Infrastructure",
    status: "Active",
    maturity: "Production",
    environment: "Production",
    icon: "Network",
    color: "from-violet-500 to-indigo-600",
    demoUrl: "/alloyscape/",
    tags: ["AI", "Orchestration", "Agents"],
    features: ["Agent orchestration", "Connector manager", "Workflow templates", "Analytics"],
    health: { status: "healthy", uptime: 99.93, responseTime: 145 },
  },
  {
    name: "Lutar",
    slug: "lutar",
    description: "Executive command center providing portfolio overview, sustainability tracking, and strategic decision support.",
    category: "Operations",
    status: "Active",
    maturity: "Production",
    environment: "Production",
    icon: "Command",
    color: "from-slate-500 to-gray-600",
    demoUrl: "/lutar/",
    tags: ["Command", "Portfolio", "Strategy"],
    features: ["Portfolio overview", "Sustainability tracker", "Decision support", "KPI dashboard"],
    health: { status: "healthy", uptime: 99.91, responseTime: 167 },
  },
  {
    name: "Lyte",
    slug: "lyte",
    description: "Deep observability platform with signal aggregation, AI analysis, MCP dashboard, and executive scorecards.",
    category: "Analytics",
    status: "Active",
    maturity: "Production",
    environment: "Production",
    icon: "Activity",
    color: "from-lime-500 to-green-600",
    demoUrl: "/lyte/",
    tags: ["Observability", "Signals", "MCP"],
    features: ["Signal aggregation", "AI analysis", "MCP dashboard", "Executive scorecard"],
    health: { status: "healthy", uptime: 99.95, responseTime: 110 },
  },
  {
    name: "Carlota Jo",
    slug: "carlota-jo",
    description: "Strategic consulting platform with client management, consultation booking, and professional advisory services.",
    category: "Business",
    status: "Active",
    maturity: "Production",
    environment: "Production",
    icon: "Briefcase",
    color: "from-rose-500 to-pink-600",
    demoUrl: "/carlota-jo/",
    tags: ["Consulting", "Business", "Advisory"],
    features: ["Client management", "Consultation flow", "Service catalog", "Payment integration"],
    health: { status: "healthy", uptime: 99.88, responseTime: 118 },
  },
  {
    name: "SZL Holdings",
    slug: "szl-holdings",
    description: "Corporate headquarters site for SZL Holdings with company overview, investor relations, and leadership information.",
    category: "Business",
    status: "Active",
    maturity: "Production",
    environment: "Production",
    icon: "Building2",
    color: "from-gold to-amber-600",
    demoUrl: "/szl-holdings/",
    tags: ["Corporate", "Branding", "Marketing"],
    features: ["Company overview", "Leadership profiles", "Investor relations", "Contact"],
    health: { status: "healthy", uptime: 99.96, responseTime: 95 },
  },
  {
    name: "Career",
    slug: "career",
    description: "Professional portfolio showcasing technical leadership, case studies, skills radar, and career timeline.",
    category: "Business",
    status: "Active",
    maturity: "Production",
    environment: "Production",
    icon: "User",
    color: "from-green-500 to-emerald-600",
    demoUrl: "/career/",
    tags: ["Portfolio", "Career", "Branding"],
    features: ["Career timeline", "Case studies", "Skills radar", "Contact form"],
    health: { status: "healthy", uptime: 99.85, responseTime: 130 },
  },
  {
    name: "Readiness Report",
    slug: "readiness-report",
    description: "Portfolio-wide readiness dashboard with project scoring, gap analysis, predictive risk assessment, and deployment tracking.",
    category: "Operations",
    status: "Active",
    maturity: "Production",
    environment: "Production",
    icon: "ClipboardCheck",
    color: "from-orange-500 to-amber-600",
    demoUrl: "/readiness-report/",
    tags: ["Operations", "Readiness", "Metrics"],
    features: ["Readiness scoring", "Gap analysis", "Risk prediction", "Deploy tracking"],
    health: { status: "healthy", uptime: 99.90, responseTime: 105 },
  },
  {
    name: "Apps Showcase",
    slug: "apps-showcase",
    description: "Centralized discovery hub for the entire SZL platform ecosystem with live status, demos, and feature catalogs.",
    category: "Platform",
    status: "Active",
    maturity: "Production",
    environment: "Production",
    icon: "LayoutGrid",
    color: "from-blue-500 to-indigo-600",
    demoUrl: "/apps-showcase/",
    tags: ["Platform", "Catalog", "Discovery"],
    features: ["App catalog", "Live demos", "Feature highlights", "Extension management"],
    health: { status: "healthy", uptime: 99.94, responseTime: 112 },
  },
];

router.get("/apps-showcase/health", (_req: Request, res: Response) => {
  res.json({ ok: true, group: "apps-showcase", timestamp: new Date().toISOString() });
});

router.get("/apps-showcase/catalog", (_req: Request, res: Response) => {
  logger.info("Apps showcase catalog requested");
  const totalApps = catalog.length;
  const healthyApps = catalog.filter(a => a.health.status === "healthy").length;
  const categories = [...new Set(catalog.map(a => a.category))];
  const avgUptime = Number((catalog.reduce((s, a) => s + a.health.uptime, 0) / totalApps).toFixed(2));

  res.json({
    catalog,
    summary: {
      totalApps,
      healthyApps,
      categories,
      avgUptime,
      lastUpdated: new Date().toISOString(),
    },
  });
});

router.get("/apps-showcase/catalog/:slug", (req: Request, res: Response) => {
  const app = catalog.find(a => a.slug === req.params.slug);
  if (!app) {
    res.status(404).json({ error: "App not found" });
    return;
  }
  res.json(app);
});

export default router;
