import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import beaconRouter from "./beacon";
import nimbusRouter from "./nimbus";
import zeusRouter from "./zeus";
import dreameraRouter from "./dreamera";
import rosieRouter from "./rosie";
import alloyRouter from "./alloy";
import agentsRouter from "./agents";
import monitoringRouter from "./monitoring";
import stripeRouter from "./stripe";
import plaidRouter from "./plaid";
import socialRouter from "./social";
import firestormRouter from "./firestorm";
import vesselsRouter from "./vessels";
import incaRouter from "./inca";
import carlotaJoRouter from "./carlota-jo";
import domainAgentsRouter from "./domain-agents";
import lyteRouter from "./lyte";
import contactRouter from "./contact";
import aegisRouter from "./aegis";
import securitySummaryRouter from "./security-summary";
import szlHoldingsRouter from "./szl-holdings";
import platformRouter from "./platform";
import { auditMiddleware } from "../lib/audit";
import { requireDatabase } from "../lib/dbGuard";
import { authRateLimit, apiRateLimit } from "../middleware/rateLimit";

const router: IRouter = Router();

router.use(auditMiddleware());
router.use(healthRouter);

router.use(apiRateLimit);

router.use("/auth", requireDatabase);
router.use("/auth", authRateLimit);
router.use("/beacon", requireDatabase);
router.use("/nimbus", requireDatabase);
router.use("/zeus", requireDatabase);
router.use("/dreamera", requireDatabase);
router.use("/rosie", requireDatabase);
router.use("/alloy", requireDatabase);
router.use("/monitoring", requireDatabase);
router.use("/inca", requireDatabase);
router.use("/vessels", requireDatabase);
router.use("/domain-agents", requireDatabase);
router.use("/aegis", requireDatabase);
router.use("/security", requireDatabase);
router.use("/carlota-jo", requireDatabase);
router.use("/szl-holdings", requireDatabase);
router.use("/platform", requireDatabase);

router.use(authRouter);
router.use(beaconRouter);
router.use(nimbusRouter);
router.use(zeusRouter);
router.use(dreameraRouter);
router.use(rosieRouter);
router.use(alloyRouter);
router.use(agentsRouter);
router.use(monitoringRouter);
router.use(stripeRouter);
router.use(plaidRouter);
router.use(socialRouter);
router.use(firestormRouter);
router.use(vesselsRouter);
router.use(incaRouter);
router.use(carlotaJoRouter);
router.use(domainAgentsRouter);
router.use(lyteRouter);
router.use(contactRouter);
router.use(aegisRouter);
router.use(securitySummaryRouter);
router.use(szlHoldingsRouter);
router.use(platformRouter);

export default router;
